/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 room.gltf --transform
Author: 3DECraft (https://sketchfab.com/3DECraft)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tiny-isometric-room-6db0b351424141099e30834c6115f40a
Title: Tiny Isometric Room
*/


import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/room-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.bed_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[-199, 100, 90]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.mattress_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[-199, 100, 90]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.desk_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[200, -20, -250]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.pouf_legs_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[-40, 100, -180]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.pouf_seat_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[-40, 125, -180]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.cupboards_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[100, 520, -300]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.book_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[-270, 474, -260]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.shoe_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[-60, 0, -50]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.wardrobe_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[299, 100, -199]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.room_lowpoly_room_material_0.geometry} material={materials.room_material} position={[0, 300, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.blanket_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[0, 0.96, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.pillow_big_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.pillow_03_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.pillow_02_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.pillow_01_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.plant_big_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[32, 180, -233]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.laptop_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[-240, 180, -260]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.sock_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[158.6, 78.06, -165.9]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.box_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[-240, 0, -240]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.toy_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[-245.71, 100.17, -196.97]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.plant_small_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[-315, 200, -39]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.fan_02_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[-153, 200, -320]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.timer_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[-319, 215, 29]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.photos_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[-99.54, 488.52, -295.39]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.shutter_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[0, 287, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.window_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[0, 300, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.fan_01_lowpoly_equipment_material_0.geometry} material={materials.equipment_material} position={[-153, 200, -320]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.ray_lowpoly_ray_material_0.geometry} material={materials.ray_material} position={[0, 300, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/room-transformed.glb')
